"""empty message

Revision ID: 19ee7e4579f4
Revises: d686ab8e3964
Create Date: 2026-07-24 12:42:10.233915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ee7e4579f4'
down_revision = 'd686ab8e3964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('preferred_theme', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_theme')
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
