"""Changed table user

Revision ID: 30da40d9227c
Revises: 91e9418d445d
Create Date: 2026-06-25 11:49:35.512724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30da40d9227c'
down_revision = '91e9418d445d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
