"""changed password field to password_hash

Revision ID: 796a68ca0b5e
Revises: 4bb705667aba
Create Date: 2026-06-25 14:36:20.722052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796a68ca0b5e'
down_revision = '4bb705667aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=180), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_public_id_key'), type_='unique')
        batch_op.drop_column('public_id')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('user_public_id_key'), ['public_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
