"""empty message

Revision ID: 9254535466c5
Revises: 19ee7e4579f4
Create Date: 2026-07-24 14:40:27.999931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9254535466c5'
down_revision = '19ee7e4579f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_theme', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('preferred_language', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
