"""empty message

Revision ID: d686ab8e3964
Revises: f03b5fd44100
Create Date: 2026-07-24 12:41:42.062971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd686ab8e3964'
down_revision = 'f03b5fd44100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_theme', sa.VARCHAR(length=1), nullable=False))
        batch_op.add_column(sa.Column('preferred_language', sa.VARCHAR(length=2), nullable=False))

    # ### end Alembic commands ###
