"""Altered table Plan

Revision ID: dd4f5423a5b4
Revises: ea339ff7a2f1
Create Date: 2026-07-12 15:14:29.179261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4f5423a5b4'
down_revision = 'ea339ff7a2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('quota_limit')

    # ### end Alembic commands ###
