"""Altered table ResetToken

Revision ID: e241f66738aa
Revises: 94edd5c24fde
Create Date: 2026-07-23 13:04:00.441431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e241f66738aa'
down_revision = '94edd5c24fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
