"""Altered table user

Revision ID: ea339ff7a2f1
Revises: f04ef965ac0d
Create Date: 2026-07-12 15:01:03.226063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea339ff7a2f1'
down_revision = 'f04ef965ac0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_quota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('master_quota')

    # ### end Alembic commands ###
