"""empty message

Revision ID: f03b5fd44100
Revises: e241f66738aa
Create Date: 2026-07-24 11:34:21.197364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b5fd44100'
down_revision = 'e241f66738aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.Enum('EN', 'ES', 'FR', 'ZH', 'RU', 'AR', name='language'), nullable=False))
        batch_op.add_column(sa.Column('preferred_theme', sa.Enum('D', 'L', name='theme'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_theme')
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
