"""empty message

Revision ID: f04ef965ac0d
Revises: 971142b46d56
Create Date: 2026-07-08 20:13:20.438032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04ef965ac0d'
down_revision = '971142b46d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
