"""empty message

Revision ID: fc0ae12c8fce
Revises: edcbcd1155e9
Create Date: 2026-08-21 22:53:01.259824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0ae12c8fce'
down_revision = 'edcbcd1155e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('billing_start')

    # ### end Alembic commands ###
